# main_agent_orchestrator.py
import os
import sys
import json
import asyncio
from google.antigravity import Agent, LocalAgentConfig, types
from sonic_mcp_server import (
    extract_fft_features, 
    extract_mel_spectrogram, 
    calculate_rhythmic_fractality,
    extract_advanced_spectral_features,
    compare_heritage_similarity_v2
)

# Absolute path of the local MCP server
server_path = os.path.abspath("sonic_mcp_server.py")

# Configure Stdio Transport for MCP
mcp_servers = [
    types.McpStdioServer(
        name="sonic_mcp",
        command=sys.executable,
        args=[server_path]
    )
]

# Configure Mathematician Agent
math_config = LocalAgentConfig(
    mcp_servers=mcp_servers,
    model="gemini-2.5-flash",
    system_instructions=(
        "You are an expert audio signal analyst specializing in musical heritage. "
        "Your task is to analyze acoustic features and compare them using acoustic distances, "
        "providing a precise numerical report in standard academic English."
    )
)

# Configure Cultural Historian Agent
anthro_config = LocalAgentConfig(
    mcp_servers=mcp_servers,
    model="gemini-2.5-flash",
    system_instructions=(
        "You are an expert music anthropologist and heritage historian. "
        "You review mathematical reports and interpret them in a cultural, historical, and contextual manner. "
        "Your goal is to examine the cross-cultural distance matrix and explain any structural connections "
        "between regional genres (e.g., traces of African polyrhythms, Tuareg desert blues, or Andalusian string traditions). "
        "Synthesize the findings directly without asking further questions. Generate a unified final cultural report immediately."
    )
)

async def run_heritage_pipeline_async(audio_path: str, context_notes: str) -> dict:
    """
    Runs the multi-agent pipeline with local feature extraction and a debate loop.
    """
    print("[1/4] Starting Multi-Agent Pipeline Session...")
    
    # 1. Invoke local signal processing tools safely
    fft_data = extract_fft_features(audio_path)
    mel_data = extract_mel_spectrogram(audio_path)
    fractal_data = calculate_rhythmic_fractality(audio_path)
    spectral_data = extract_advanced_spectral_features(audio_path)
    
    # 2. Run similarity distance engine V2
    print("[2/4] Executing Cross-Cultural Acoustic Distance Engine V2...")
    comparison_data = compare_heritage_similarity_v2(
        estimated_bpm=spectral_data['estimated_bpm'],
        spectral_centroid=spectral_data['spectral_centroid_hz'],
        spectral_flatness=spectral_data['spectral_flatness']
    )
    
    # Pack metrics for agent context
    raw_sonic_metrics = {
        "fft": fft_data,
        "mel": mel_data,
        "fractal": fractal_data,
        "spectral_advanced": spectral_data,
        "standardized_distance_matrix": comparison_data
    }
    
    async with Agent(math_config) as math_agent:
        async with Agent(anthro_config) as anthro_agent:
            
            # Step 1: Mathematician processes the raw features
            print("[3/4] Running Mathematician analysis on structural metrics...")
            math_prompt = f"Please analyze the following mathematical features and similarity measurements, and generate a concise technical report: {json.dumps(raw_sonic_metrics)}"
            math_response = await math_agent.chat(math_prompt)
            math_report = await math_response.text()
            print(">>> Mathematician Report Generated.")
            
            # Step 2: Historian reviews findings and writes first draft
            print("[4/4] Anthropologist reviewing mathematical findings and cross-cultural distance...")
            anthro_prompt = (
                f"Here is the report generated by the Mathematician:\n{math_report}\n\n"
                f"Here is the output from the distance engine:\n{json.dumps(comparison_data)}\n\n"
                f"Here are the field context notes:\n{context_notes}\n\n"
                "Generate an anthropological report interpreting these acoustic distances and connections. "
                "If you have any questions or find any conflicts, ask the Mathematician to clarify specific features "
                "(like spectral centroid or rhythmic flatness) to resolve the issue."
            )
            anthro_response = await anthro_agent.chat(anthro_prompt)
            anthro_report = await anthro_response.text()
            print(">>> Anthropologist First Review Completed.")
            
            # Step 3: Trigger debate loop if questions/discrepancies are raised
            final_report = anthro_report
            if "?" in anthro_report or "question" in anthro_report.lower() or "clarify" in anthro_report.lower() or "discrepancy" in anthro_report.lower():
                print("[Pipeline] Conflict or clarification detected! Triggering debate loop...")
                
                debate_prompt = (
                    f"The anthropologist raised the following questions or requested clarifications:\n{anthro_report}\n\n"
                    "Please re-examine the structural data and clarify the mathematical features to resolve the conflict."
                )
                debate_response = await math_agent.chat(debate_prompt)
                math_clarification = await debate_response.text()
                print(">>> Mathematician Clarified Findings.")
                
                # Step 4: Final consolidated report
                final_prompt = (
                    f"Here is the final clarification from the Mathematician:\n{math_clarification}\n\n"
                    "Please write the final consolidated anthropological report with a cohesive and unified cultural narrative."
                )
                final_response = await anthro_agent.chat(final_prompt)
                final_report = await final_response.text()
                print(">>> Final Consolidated Report Generated.")
            else:
                print("[Pipeline] No debate required. Finalizing report...")
                
            return {
                "metrics": raw_sonic_metrics,
                "math_report": math_report,
                "cultural_report": final_report
            }

def run_heritage_pipeline(audio_path: str, context_notes: str):
    """Synchronous wrapper for external pipeline execution."""
    return asyncio.run(run_heritage_pipeline_async(audio_path, context_notes))

if __name__ == "__main__":
    # Local execution test
    test_audio = "trim_Zina Daoudia - Meriem [Official Music Video] (2026)  زينة الداودية - مريم.wav"
    test_notes = "Unknown origin. Please analyze the acoustic features and determine the cultural taxonomy."
    
    if os.path.exists(test_audio):
        res = run_heritage_pipeline(test_audio, test_notes)
        print("\n================ FINAL RESULTS ================")
        report_text = res["cultural_report"]
        print("CULTURAL REPORT:\n", report_text)
        
        # Save the report to a markdown file
        with open("heritage_acoustic_report.md", "w", encoding="utf-8") as f:
            f.write(report_text)
        print("\n[✔] The report has been successfully saved to 'heritage_acoustic_report.md'")
    else:
        print("Test audio file not found. Please verify the path.")